<?php
/**
 * Created by PhpStorm.
 * User: misha
 * Date: 03.09.17
 * Time: 20:56
 */

namespace Mvc\Components;


use Mvc\Application\Models\User;
use Mvc\Core\MvcKernel;

class MyKernel extends MvcKernel
{
    /**
     * @var $user User
     */
    public $user = null;


    public function beforeAction()
    {
        if(isset($_SESSION['user'])){
            $this->user = $_SESSION['user'];
        }
        parent::beforeAction(); // TODO: Change the autogenerated stub
    }
}