assets:
    basePath: '/web/'
    js:
        - 'js/jquery-3.1.1.min.js'
        - 'js/custom.js'
    css:
        - 'css/bootstrap.css'
        - 'css/bootstrap-grid.css'
        - 'css/bootstrap-reboot.css'
        - 'css/custom.css'
